[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
ffi = true
fs_permissions = [
    { access = "read", path = "./" }
]
gas_reports = ["IdentityToken", "ReputationBadge", "BadgeRuleRegistry"]

[fmt]
line_length = 120
